version: '3.8'

networks:
  mssqlnet:
    driver: bridge

services:
  mssql:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mssql
    ports:
      - 1433:1433
      - 14322:22
    restart: always
    volumes:
      - ./mssql-data:/var/opt/mssql:rw
    networks:
      - mssqlnet